version: "3"
services:
  front:
    container_name: front
    build:
      context: .
      dockerfile: front/Dockerfile
    restart: always
    ports:
      - 3001:3001

  back:
    container_name: back
    build:
      context: back
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
